DROP TABLE CONFIGURATION IF EXISTS;
CREATE TABLE CONFIGURATION(KEY VARCHAR(256) NOT NULL PRIMARY KEY,VALUE VARCHAR(256));

insert into CONFIGURATION  (KEY,VALUE) VALUES ('First','1');
insert into CONFIGURATION  (KEY,VALUE) VALUES ('Second','2');
insert into CONFIGURATION  (KEY,VALUE) VALUES ('Third','3');